CREATE TABLE board (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    squareOne INTEGER NOT NULL,
    squareTwo INTEGER NOT NULL,
    squareThree INTEGER NOT NULL,
    squareFour INTEGER NOT NULL,
    squareFive INTEGER NOT NULL,
    squareSix INTEGER NOT NULL,
    squareSeven INTEGER NOT NULL,
    squareEight INTEGER NOT NULL,
    squareNine INTEGER NOT NULL,
);

CREATE TABLE game (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_ended TIMESTAMP,
    player_started_id INTEGER,
    player_joined_id INTEGER,
    board ??? i dont know what should go here
);

